<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_CrossLocationReportIcon</name>
   <tag></tag>
   <elementGuidId>80c57e40-ac88-4ff9-9e11-c16d6a2ef913</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='sidepanel-wraper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='sidepanel-wraper']</value>
   </webElementProperties>
</WebElementEntity>
