<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dtp_EndMonthValue</name>
   <tag></tag>
   <elementGuidId>e379d18c-7178-45fe-9247-8fca5d27ae74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class='dp-nav-header']//span)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='dp-nav-header']//span)[2]</value>
   </webElementProperties>
</WebElementEntity>
