<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LaborBudget</name>
   <tag></tag>
   <elementGuidId>8382d134-d4fb-49ca-982c-577e124f4a1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;main-field&quot;]/div/div/div[2]/div[1]/table/tbody/tr/td[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;main-field&quot;]/div/div/div[2]/div[1]/table/tbody/tr/td[3]/input</value>
   </webElementProperties>
</WebElementEntity>
