<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>collapse_Actual</name>
   <tag></tag>
   <elementGuidId>e08ed14a-78a5-4a4e-adb1-b542c287485e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()='Actual']//parent::label//following-sibling::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()='Actual']//parent::label//following-sibling::button[1]</value>
   </webElementProperties>
</WebElementEntity>
