<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cld2_backbtn</name>
   <tag></tag>
   <elementGuidId>dbc34182-6389-4c0c-9bd8-31f3d4b0c7d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//button[contains(@class,'dp-calendar-nav-left')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//button[contains(@class,'dp-calendar-nav-left')])[2]</value>
   </webElementProperties>
</WebElementEntity>
