<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>expand_Budget</name>
   <tag></tag>
   <elementGuidId>a72d9261-9e47-4e88-97d9-627f032df38e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()='Budget']//parent::label//following-sibling::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()='Budget']//parent::label//following-sibling::button[1]</value>
   </webElementProperties>
</WebElementEntity>
