<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drp_locations</name>
   <tag></tag>
   <elementGuidId>7a9a5218-0c0d-4cd0-aee3-2509fb73e085</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[@class='ng-arrow-wrapper'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[@class='ng-arrow-wrapper'])[1]</value>
   </webElementProperties>
</WebElementEntity>
