<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ThresholdValue</name>
   <tag></tag>
   <elementGuidId>3e94b51e-116f-45bf-9c1e-813fdb42cd63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@formcontrolname='iFromValue'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@formcontrolname='iFromValue'])[1]</value>
   </webElementProperties>
</WebElementEntity>
