<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ColumnName</name>
   <tag></tag>
   <elementGuidId>1cfe5507-348e-42bf-b710-d3cbe4d1d9f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@name='strColumnDisplayName'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@name='strColumnDisplayName'])[1]</value>
   </webElementProperties>
</WebElementEntity>
