<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_openColumnsName</name>
   <tag></tag>
   <elementGuidId>8e6bf095-0bc6-4dc9-a5ca-534154d23a98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@formcontrolname='strColumnName'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@formcontrolname='strColumnName'])[1]</value>
   </webElementProperties>
</WebElementEntity>
