<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_ColumnName</name>
   <tag></tag>
   <elementGuidId>0d6237bf-de38-46fa-91dd-ae7cb45c97fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@formcontrolname='strColumnName'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@formcontrolname='strColumnName'])[1]</value>
   </webElementProperties>
</WebElementEntity>
